name: Health Check tests

on:
  push:
    branches:
      - master
    paths:
      - python/**
      - reports/*.qmd
      - .github/workflows/**
  pull_request: 
    paths:
      - python/**
      - reports/*.qmd

jobs:
  HealthCheck-Test:
    runs-on: ubuntu-latest
    name: Test Health Check
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        working-directory: python
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install -y pandoc

      - uses: actions/checkout@v2
      - name: "Install quarto"
        run: |
          #        curl -OL https://github.com/quarto-dev/quarto-cli/releases/download/v0.1.258/quarto-0.1-amd64.deb
          curl -s https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest | 
          grep "browser_download_url.*deb" | 
          cut -d '"' -f 4 |
          wget -i -
          sudo dpkg -i quarto-0.1-amd64.deb

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
          pip install pytest-cov
          pip install scipy
          pip install testbook
          pip install XlsxWriter
          pip install ipython 
          pip install ipykernel
          ipython kernel install --name "python3" --user

      - name: Run tests
        run: pytest python/tests/test_healthcheck.py
