name: Health Check tests

on:
  push:
    branches:
      - master
    paths:
      - python/**
      - reports/*.qmd
      - .github/workflows/**
  pull_request: 
    paths:
      - python/**
      - reports/*.qmd

jobs:
  HealthCheck-Test:
    runs-on: ubuntu-latest
    name: Test Health Check
    steps:
      - uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.450
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        working-directory: python
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/test-requirements.txt
          pip install papermill
          pip install itables
          pip install jinja2
          ipython kernel install --name "python3" --user
          sudo apt-get install -y pandoc
          
      - name: Install pdstools
        run: pip install .

      - name: Run Health Check
        run: pytest python/tests/test_healthcheck.py
